name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-validate-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
            pip install poetry
            poetry install

      - name: Run ruff
        uses: astral-sh/ruff-action@v1.1.1

      - name: Validate build
        run: poetry build

      - name: Run tests
        run: |
          source $(poetry env info --path)/bin/activate
          pytest

      - name: Create a tag
        run: |
          # Extract version from pyproject.toml using python
          VERSION=$(python -c 'import toml; print(toml.load("pyproject.toml")["tool"]["poetry"]["version"])')
          echo "Creating tag v$VERSION"

          git tag -a "v$VERSION" -m "Release version $VERSION"
          git push origin "v$VERSION"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
